import { useState } from "react";
import toast from "react-hot-toast";
import { CalendarPlus, Download, UserPlus } from "lucide-react";
import { Button } from "../../components/ui/Button";
import { Field, Input, Select } from "../../components/ui/Form";
import { Modal } from "../../components/ui/Modal";
import { StudentPicker } from "../../components/ui/StudentPicker";
import { EmptyState, PageHeader, Spinner } from "../../components/ui/Feedback";
import { Table, Td, Th, Thead, Tr } from "../../components/ui/Table";
import { downloadCsv } from "../../lib/csvExport";
import { formatDate, formatDuration, todayIso } from "../../lib/format";
import { useAddCoachingEnrollment, useCoachingClasses, useCoachingEnrollments, useCreateCoachingClass, useCreateExternalParticipant, useCreateInstructor, useDeleteCoachingClass, useExternalParticipants, useInstructors } from "../../api/coaching";
import type { ExternalParticipant, Student } from "../../api/types";

export function CoachingClassesPage() {
  const { data: sessions, isLoading } = useCoachingClasses();
  const [selectedId, setSelectedId] = useState<number>();
  const [modal, setModal] = useState<"session" | "instructor" | "external" | "participant" | null>(null);
  const selected = sessions?.find(s => s.class_id === selectedId) ?? sessions?.[0];
  return <div>
    <PageHeader eyebrow="Coaching centre" title="Coaching classes" description="Create sessions, reuse instructors and external-student profiles, and enroll attendees." action={<div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => setModal("instructor")}>Add Instructor</Button><Button variant="secondary" onClick={() => setModal("external")}>Add External Student</Button><Button onClick={() => setModal("session")}><CalendarPlus size={16}/> Add New Session</Button></div>}/>
    {isLoading && <Spinner label="Loading coaching sessions…"/>}
    {!isLoading && !sessions?.length && <EmptyState title="No coaching sessions" description="Create a session to begin enrolling attendees."/>}
    {!!sessions?.length && <div className="grid gap-6 xl:grid-cols-[18rem_1fr]"><aside className="rounded-xl border border-border bg-card p-3"><p className="px-3 py-2 text-xs font-semibold uppercase tracking-wider text-slate">Sessions</p>{sessions.map(s => <button key={s.class_id} onClick={() => setSelectedId(s.class_id)} className={`mb-1 w-full rounded-lg p-3 text-left ${selected?.class_id === s.class_id ? "bg-ink text-paper" : "hover:bg-paper-dim"}`}><p className="font-medium">{s.title}</p><p className="mt-1 text-xs opacity-70">{formatDate(s.class_date)} · {s.instructor_name ?? "No instructor"}</p></button>)}</aside>{selected && <Roster session={selected} onAdd={() => setModal("participant")}/>}</div>}
    <SessionForm open={modal === "session"} onClose={() => setModal(null)}/><InstructorForm open={modal === "instructor"} onClose={() => setModal(null)}/><ExternalForm open={modal === "external"} onClose={() => setModal(null)}/>{selected && <ParticipantForm open={modal === "participant"} onClose={() => setModal(null)} classId={selected.class_id}/>}</div>;
}
function Roster({ session, onAdd }: { session: import("../../api/types").CoachingClass; onAdd: () => void }) { const { data } = useCoachingEnrollments(session.class_id); const remove = useDeleteCoachingClass(); const exportRows = () => downloadCsv(`coaching-${session.class_id}`, (data ?? []).map(x => ({ session: session.title, date: session.class_date, participant: x.participant_name, type: x.participant_type, village: x.village, phone: x.phone, duration_minutes: session.duration_minutes }))); return <section className="rounded-xl border border-border bg-card"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-border p-5"><div><p className="text-xs font-semibold uppercase tracking-wider text-brass">Session workspace</p><h2 className="font-display text-xl font-semibold">{session.title}</h2><p className="mt-1 text-sm text-slate">{formatDate(session.class_date)} · {formatDuration(session.duration_minutes)} · {data?.length ?? 0} attendees</p></div><div className="flex gap-2"><Button variant="secondary" onClick={exportRows}><Download size={15}/> Export CSV</Button><Button variant="ghost" onClick={() => window.print()}>PDF</Button><Button variant="ghost" onClick={() => { if (confirm("Delete this coaching session?")) remove.mutate(session.class_id); }}>Delete Session</Button><Button onClick={onAdd}><UserPlus size={16}/> Add participant</Button></div></div><div className="p-3">{!data?.length ? <EmptyState title="No attendees" description="Adding a participant confirms their attendance."/> : <Table><Thead><Th>Participant</Th><Th>Type</Th><Th>Village</Th><Th>Phone</Th></Thead><tbody>{data.map(x => <Tr key={x.enrollment_id}><Td className="font-medium">{x.participant_name}{x.student_id && <span className="ml-2 font-mono text-xs text-slate">#{x.student_id}</span>}</Td><Td>{x.participant_type}</Td><Td>{x.village ?? "—"}</Td><Td>{x.phone ?? "—"}</Td></Tr>)}</tbody></Table>}</div></section>; }
function SessionForm({ open, onClose }: { open: boolean; onClose: () => void }) { const create = useCreateCoachingClass(); const { data: instructors } = useInstructors(); const [title,setTitle]=useState(""); const [date,setDate]=useState(todayIso()); const [start,setStart]=useState(""); const [end,setEnd]=useState(""); const [instructor,setInstructor]=useState(""); const submit=async(e:React.FormEvent)=>{e.preventDefault();try{await create.mutateAsync({title,class_date:date,start_time:start||null,end_time:end||null,subject:null,instructor_id:instructor?Number(instructor):null,notes:null});toast.success("Session created");onClose()}catch{toast.error("Could not create session")}}; return <Modal open={open} onClose={onClose} title="Add New Session"><form onSubmit={submit} className="space-y-4"><Field label="Session title" required><Input required value={title} onChange={e=>setTitle(e.target.value)}/></Field><div className="grid grid-cols-3 gap-3"><Field label="Date" required><Input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Class start time"><Input type="time" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Class end time"><Input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></Field></div><Field label="Instructor"><Select value={instructor} onChange={e=>setInstructor(e.target.value)}><option value="">Select instructor</option>{instructors?.map(i=><option key={i.instructor_id} value={i.instructor_id}>{i.name}</option>)}</Select></Field><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit">Save session</Button></div></form></Modal>; }
function InstructorForm({open,onClose}:{open:boolean;onClose:()=>void}){const create=useCreateInstructor();const [name,setName]=useState("");const [phone,setPhone]=useState("");return <Modal open={open} onClose={onClose} title="Add Instructor"><form onSubmit={async e=>{e.preventDefault();await create.mutateAsync({name,phone:phone||null,specialization:null,notes:null});toast.success("Instructor added");onClose()}} className="space-y-4"><Field label="Instructor name" required><Input required value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Phone"><Input value={phone} onChange={e=>setPhone(e.target.value)}/></Field><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit">Add Instructor</Button></div></form></Modal>}
function ExternalForm({open,onClose}:{open:boolean;onClose:()=>void}){const create=useCreateExternalParticipant();const [name,setName]=useState("");const [village,setVillage]=useState("");return <Modal open={open} onClose={onClose} title="Add External Student"><form onSubmit={async e=>{e.preventDefault();await create.mutateAsync({name,village,phone:null,gender:null,guardian_name:null,notes:null});toast.success("External student added");onClose()}} className="space-y-4"><Field label="Student name" required><Input required value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Village" required><Input required value={village} onChange={e=>setVillage(e.target.value)}/></Field><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit">Add External Student</Button></div></form></Modal>}
function ParticipantForm({open,onClose,classId}:{open:boolean;onClose:()=>void;classId:number}){const add=useAddCoachingEnrollment(classId);const [type,setType]=useState("Library Student");const [student,setStudent]=useState<Student|null>(null);const [search,setSearch]=useState("");const {data:external}=useExternalParticipants(search);const [picked,setPicked]=useState<ExternalParticipant>();return <Modal open={open} onClose={onClose} title="Add attendee"><form onSubmit={async e=>{e.preventDefault();if(type==='Library Student'&&student)await add.mutateAsync({participant_type:'Library Student',student_id:student.student_id});if(type==='External Student'&&picked)await add.mutateAsync({participant_type:'External Student',external_participant_id:picked.external_participant_id});onClose()}} className="space-y-4"><Select value={type} onChange={e=>setType(e.target.value)}><option>Library Student</option><option>External Student</option></Select>{type==='Library Student'?<StudentPicker value={student} onChange={setStudent}/>:<><Input placeholder="Search by name, village, or phone" value={search} onChange={e=>setSearch(e.target.value)}/><Select value={picked?.external_participant_id??""} onChange={e=>setPicked(external?.find(x=>x.external_participant_id===Number(e.target.value)))}><option value="">Select external student</option>{external?.map(x=><option key={x.external_participant_id} value={x.external_participant_id}>{x.name} · {x.village}</option>)}</Select></>}<div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit">Add attendee</Button></div></form></Modal>}
